language: node_js
addons:
  apt:
    packages:
    - sshpass
node_js:
- 8.6.0
before_script: npm install
script: npm run test
after_success:
- sshpass -p $DEPLOY_PASS ssh $DEPLOY_USER@$DEPLOY_HOST
- mkdir test
- cd /var/www/avalon
- git pull
env:
  global:
  - secure: "KDGstwzwmvLh7nqWicms7WK6XCskwZ/MXSLeLA8dx/FKqRr1f/ropu/q59xdPyxG7zAA1maIlMW/pILryb5cuxL/ev7Enz+/liSGFvAL/cR8OTg1/8z46gyYbjrtt8+91qomMcT3AhdnnGT/wKFoGljHLhfFBm5HMLbIxI/X+HIuJfSyuWYFZan8IigcM9VvzBYnR7Y+mT/olT3148u1qBAj7RW0pK+a7aoXeGTiBut2pMlVh0U/BBqwMlaXYD0Dl2KlEz6BPwFrsXrR01d7udXR5A3oKafErZB1HmuJJumxN+tvC5GBXz7AiuRpeD1/NpgT5oXviVJveORKOul5BLNZ7AwA0UFWgmLTplV4AHfIOryETPtyc/eURNo7k5P5IycPBZiNuJiYPxu5gpXI2WFK6PoLkhWnLc9EDsBebRuF80717FA6Pu8ONi79NJeQkeuCemVojlDRt558+O39Zstj73a6fujJTpiCPJtto8MhHSQ4+SjmmDceXdJSdzGTxEPV6WKIhKZFNbgVWPTFk9yhHf/ix1CvSIH5DGifvZQijIsTIGdc+37CbwAHzT1iUVwH5s9FySaHyWQGAyBk1IKU3JpLmgmQvAwAkhjF/efvLlTqjJaXA+T+bMkA6ErEQb2tCijFdNFIwU9UZ3cksaXBwPDY/0WelTkJvuxPPGs="
  - secure: "csZlhYuupBUvNYvxA3PjsQ6L4yQJQHIdMYRm4w9yBSL5+1Bhxe7brvzwxX7rx0fIe7uS2AQjSAHunvOCxz72PWy+LF3B6GRidiMYRzAkc5B7gfnHKiA1SiRs+eABH9g1vxm4j1I1j+cdBHTmwF0bX9HQdeZtbFuCQdTDy/iFXkigrMUldAXLZnZxYznWxsKn48P2k+niL9ofbl9rNwXSHc0xmTihRr60N2EiuD95Ht5GH8GxZ4KGKTBMICa+DKPnIzup/AwhTw0NcNsOsyaibOQ4TLEVh45eQ21m+UC4hp500fGqdBNZAWe0zShIRyDoWngthp3TLEr3JWWGOZHfXPBejuVLl1EoGgM78namtjfnhHdfFffXRTnnEiYFc5Z9DGvi7tl8GfRjDY95EPOCbDnnDYG1GfqGDRGysxbEZO8AA6V52tefDau8UB/c1CdqSp62jthhBWfm8XP21+fyqtFeYgTvlki3iWhrauHD0EuFCig1e1Gco7/KM+pqfWibKoKu3WRd5L+qbhLvtezQ4ujVPgJuo9Xbqc11oFfpRJtHtWPAimzi8TfbyZxkiMNQLUfucJmufh8AAMqrSpq5zX+hh+zk/mvLjyDwQoHoLsfRE7uD4QeBwAeLcnRbS6jgabLfk83Qjw5/ON2kEmF7N+Jsq5hiDFa1J8GBfmRRTDI="
  - secure: "abUwz1VZgST4r2kveJCFpkoZhfUcU9oXolJqD3MGrZtAB7nLNsUAUppNGdjhAMCUJEO+pSeGGyC6u+XfzkLfp7MwbhTZ93YTiJekk3t+Dlv12Xp8oUaPnuNfMUuM93Xx48pZmmhULRav7dyhycwDZP4iUA354R1JFJ0Hd5+KGC9PQFJHmEDs5fIHhwZLf0/ad9wUkIJlwd9kFDMYi7RlvTGbTrEmxxGwkcpaUWvVSVRAoG4uIvKCjHH5ZgtZGmax0HwTAX/Y6cwOBR7EzAactPVSsU8pDQCZWeDqYb/L6lWdxQuvRALpaqt34YESpTF8KPsJu6yRDKA4Zi/J2tacR1CvdDYCPQA4JARbxSfPFhsi9SowFb4mOZdz/PvX4KDOQ0lCx4SU3RvJNyT1j+YQMBTyjvlwLwOXJX1ClxxTMWINrefPa0BpqOKHHGsgomxO3U7bqOjKLYK4/GF3k9902yzmUuz0eTKNckdlT0ydt+f6JLNyj7VkkmONq2AJ04Taa2dRWg4rPzVp0uCSt2RE/e1iv5WSLJNsoPiRBLcOO6PfYsTpKUAV2+h2gh9bRTjKcw/rIltjExngib+WA/hX3WGWuV2Fmbg5LRil9S/eTztQlDhFBcfbrR4QIACxo2NWjyQQ/JPAcT01KLSHjbHly7VnSGH9JNzgzewy7jNsUvY="
